name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.8
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  month_year_picker: 0.2.0+3
  simple_month_year_picker: ^0.0.2
  flutter_month_picker: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
